import "./globals.css";
import { League_Spartan } from "next/font/google";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const league_spartan = League_Spartan({ subsets: ["latin"] });

export const metadata = {
  title: "Arch Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-gray-200">
      <body
        className={`${league_spartan.className} max-w-[1440px] mx-auto bg-white text-[18px] leading-normal relative`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
